version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build || echo "Build failed!"
      - echo "Checking root directory contents..."
      - ls -la || echo "Root directory is empty!"
      - echo "Checking .next folder..."
      - ls -la .next || echo ".next folder not found!"
      - mkdir -p artifact
      - cp -R .next public package.json package-lock.json artifact/ || echo "Failed to copy files!"
      - echo "Packaging files into app.zip..."
      - zip -r app.zip artifact/*
artifacts:
  files:
    - app.zip
