version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm ci # Clean install dependencies

  build:
    commands:
      - echo "Building the application..."
      - npm run build # Build the Next.js application
      - echo "Build completed successfully."
  
artifacts:
  files:
    - '**/*'
  base-directory 'build'
cache:
  paths:
   - 'node_modules/**/*'
