version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm ci # Clean install dependencies

  build:
    commands:
      - echo "Building the application..."
      - npm run build # Build the Next.js application
      - echo "Build completed successfully."
      - echo "Checking the directory structure after the build:"
      - ls -R # List all files recursively for debugging

  post_build:
    commands:
      - echo "Packaging the application for deployment..."
      # Package files from both the app directory and the root production files
      - zip -r app.zip .next app package.json package-lock.json public next.config.mjs
      - echo "Contents of app.zip:"
      - unzip -l app.zip # List the contents of the zip file
      - echo "Build and packaging completed."

artifacts:
  files:
    - app.zip
