version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Ensure the Node.js version matches your requirements
    commands:
      - echo "Installing dependencies..."
      - npm ci # Install dependencies at the root or adjust to the correct directory

  build:
    commands:
      - echo "Building the application..."
      - npm run build # Adjust this command if it needs to run in a specific directory
      - echo "Build completed successfully."
      - echo "Checking the .next directory:"
      - ls -al .next || echo ".next directory not found!"

  post_build:
    commands:
      - echo "Packaging the application for deployment..."
      - zip -r app.zip .next package.json package-lock.json public next.config.mjs
      - echo "Contents of app.zip:"
      - unzip -l app.zip
      - echo "Build and packaging completed."

artifacts:
  files:
    - app.zip
  discard-paths: no # Maintain the file structure

