version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22 # Ensure this matches your app's Node.js version
    commands:
      - echo Installing dependencies...
      - npm ci # Clean install all dependencies
  build:
    commands:
      - echo Building the application...
      - npm run build # Build the Next.js application
  post_build:
    commands:
      - echo Packaging the application for deployment...
      - zip -r app.zip .next package.json package-lock.json public next.config.mjs
      - echo Build and packaging completed.
artifacts:
  files:
    - app.zip